# - name: Fetch current IP address
#   shell: curl -s https://ipinfo.io/ip
#   register: current_ip

# - name: Update IP in configuration file
#   shell: |
#     sed -i "s=<IP>.*</IP>=<IP>{{ current_ip.stdout }}</IP>=g" {{ config_dir }}

# - name: Count plugins in plugin directory
#   shell: ls -1 "{{ plugin_dir }}"/*.dll | wc -l
#   register: plugin_count

# - name: Format plugins into XML
#   shell: |
#     if [ "{{ plugin_count.stdout }}" -gt "0" ]; then
#       PLUGINS_STRING="<Plugins>$(ls -1 {{ plugin_dir }}/*.dll | \
#       sed -E 's=(.+\.dll)=<string>\\1</string>=g' | \
#       tr -d '\\n' )</Plugins>"
#     else
#       PLUGINS_STRING="<Plugins />"
#     fi
#     echo "$PLUGINS_STRING"
#   register: plugins_string

# - name: Remove old log files
#   shell: rm {{ instance_dir }}/{{ instance_name }}/*.log

- name: Replace LoadWorld path in .cfg
  shell: |
    # Define the path to the configuration file
    CONFIG_FILE="/appdata/space-engineers/instances/SE_TEST/SpaceEngineers-Dedicated.cfg"
    
    # Step 1: Extract the WORLD_NAME from the <LoadWorld> string using sed
    WORLD_NAME=$(sed -n 's|.*Saves\([^<]*\)\Sandbox.sbc.*|\1|p' "$CONFIG_FILE")
    
    # Check if the WORLD_NAME was successfully extracted
    if [ -z "$WORLD_NAME" ]; then
        echo "WORLD_NAME extraction failed!"
        exit 1
    fi
    
    NEW_LOADWORLD="<LoadWorld>Z:\\\\appdata\\\\space-engineers\\\\instances\\\\SE_TEST\\\\Saves\\$WORLD_NAME\\\\Sandbox.sbc</LoadWorld>"
    
    # Use sed to replace the <LoadWorld> line
    sed -i "s|<LoadWorld>.*</LoadWorld>|$NEW_LOADWORLD|" "$CONFIG_FILE"
    
    # Confirm replacement and run additional scripts
    echo "Replaced <LoadWorld> with the new path."
