- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist

- name: Enable 32-bit architecture for Wine
  apt:
    name: dpkg
    state: present

- name: Add i386 architecture to support 32-bit packages
  command: dpkg --add-architecture i386

- name: Create directory for WineHQ repository key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add the WineHQ repository key
  get_url:
    url: https://dl.winehq.org/wine-builds/winehq.key
    dest: /etc/apt/keyrings/winehq-archive.key
    mode: '0644'

- name: Add the WineHQ repository for Debian Bullseye
  get_url:
    url: https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources
    dest: /etc/apt/sources.list.d/winehq-bullseye.sources
    mode: '0644'

- name: Update package cache after adding WineHQ repository
  apt:
    update_cache: yes

- name: Install Wine (Stable Branch) and required dependencies
  apt:
    name:
      - winehq-stable
      - wine64
      - wine32
      - lib32gcc-s1
      - libmono-cil-dev  # Ensure Mono is installed
      - lib32z1  # Needed for Wine (32-bit zlib support)
    state: present
    install_recommends: yes

- name: Install Wine Mono
  shell: |
    wget https://dl.winehq.org/wine/wine-mono/9.4.0/wine-mono-9.4.0-x86.msi -O /tmp/wine-mono.msi
    wine msiexec /i /tmp/wine-mono.msi
  args:
    creates: "/root/.wine/drive_c/windows/mono"

- name: Install Wine Gecko
  shell: |
    wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi -O /tmp/wine-gecko.msi
    wine msiexec /i /tmp/wine-gecko.msi
  args:
    creates: "/root/.wine/drive_c/windows/gecko"

- name: Install X11 and virtual framebuffer
  apt:
    name:
      - xvfb
      - x11-utils
      - xserver-xorg
    state: present

- name: Pre-configure Wine prefix
  shell: winecfg
  args:
  
    creates: "/root/.wine/system.reg"

- name: Configure Wine to use a virtual desktop
  shell: |
    xvfb-run winecfg -v
    echo -e "[Software\\Wine\\X11 Driver]\\n\"UseTakeFocus\"=\"N\"" | xvfb-run wine regedit
  args:
    creates: "/root/.wine/config"
  async: 1800  
  poll: 60    
