- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist

- name: Enable 32-bit architecture for Wine
  apt:
    name: dpkg
    state: present

- name: Add i386 architecture to support 32-bit packages
  command: dpkg --add-architecture i386

- name: Create directory for WineHQ repository key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add the WineHQ repository key
  get_url:
    url: https://dl.winehq.org/wine-builds/winehq.key
    dest: /etc/apt/keyrings/winehq-archive.key
    mode: '0644'

- name: Add the WineHQ repository for Debian Bullseye
  get_url:
    url: https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources
    dest: /etc/apt/sources.list.d/winehq-bullseye.sources
    mode: '0644'

- name: Update package cache after adding WineHQ repository
  apt:
    update_cache: yes

- name: Install Wine (Stable Branch) and required 32-bit dependencies
  apt:
    name:
      - winehq-stable
      - wine32  # Ensure 32-bit Wine is installed
      - lib32gcc-s1  # 32-bit GCC support
      - lib32z1  # 32-bit zlib support
      - libmono-cil-dev  # Mono for Wine
      - xvfb
      - x11-utils
      - xserver-xorg
    state: present
    install_recommends: yes

- name: Install Wine Mono for 32-bit
  shell: |
    wget https://dl.winehq.org/wine/wine-mono/9.4.0/wine-mono-9.4.0-x86.msi -O /tmp/wine-mono.msi
    WINEARCH=win32 WINEPREFIX=/root/.wine wine msiexec /i /tmp/wine-mono.msi
  args:
    creates: "/root/.wine/drive_c/windows/mono"

- name: Install Wine Gecko for 32-bit
  shell: |
    wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi -O /tmp/wine-gecko.msi
    WINEARCH=win32 WINEPREFIX=/root/.wine wine msiexec /i /tmp/wine-gecko.msi
  args:
    creates: "/root/.wine/drive_c/windows/gecko"

- name: Pre-configure Wine prefix for 32-bit
  shell: |
    WINEARCH=win32 WINEPREFIX=/root/.wine winecfg
  args:
    creates: "/root/.wine/system.reg"

- name: Configure Wine to use a virtual desktop (Optional)
  shell: |
    xvfb-run WINEARCH=win32 WINEPREFIX=/root/.wine winecfg -v
    echo -e "[Software\\Wine\\X11 Driver]\\n\"UseTakeFocus\"=\"N\"" | xvfb-run WINEARCH=win32 WINEPREFIX=/root/.wine wine regedit
  args:
    creates: "/root/.wine/config"
    async: 1800
    poll: 60
