- name: Install Space Engineers Dedicated Server via SteamCMD
  command: /usr/games/steamcmd +force_install_dir {{ game_dir }} +login anonymous +@sSteamCmdForcePlatformType windows +app_update 298740 +quit

- name: Configure Space Engineers Dedicated Server
  block:

    - name: Update IP address in configuration
      lineinfile:
        path: "{{ instances_dir }}/{{ instance_name }}/SpaceEngineers-Dedicated.cfg"
        regexp: '<IP>.*</IP>'
        line: "<IP>{{ ansible_default_ipv4.address }}</IP>"

    - name: Update world save path in configuration
      lineinfile:
        path: "{{ instances_dir }}/{{ instance_name }}/SpaceEngineers-Dedicated.cfg"
        regexp: '<LoadWorld.*LoadWorld>'
        line: "<LoadWorld>Z:\\\appdata\\space-engineers\\instances\\{{ instance_name }}\\Saves\\{{ world_name }}</LoadWorld>"

    - name: Update plugins in configuration
      block:
        - name: Count plugins
          find:
            paths: "{{ plugin_dir }}"
            patterns: "*.dll"
          register: plugin_list

        - name: Add plugins to configuration
          lineinfile:
            path: "{{ instances_dir }}/{{ instance_name }}/SpaceEngineers-Dedicated.cfg"
            regexp: '<Plugins.*Plugins>'
            line: "<Plugins>{{ plugin_list.files | map('basename') | join(', ') }}</Plugins>"

- name: Start Space Engineers Dedicated Server
  command: |
    wine SpaceEngineersDedicated.exe -noconsole -ignorelastsession -path Z:\appdata\space-engineers\instances\{{ instance_name }}
  args:
    chdir: "{{ game_dir }}/DedicatedServer64"

- name: Health Check
  uri:
    url: "https://api.steampowered.com/ISteamApps/GetServersAtAddress/v1?addr={{ ansible_default_ipv4.address }}"
    method: GET
    status_code: 200
