- name: Create Space Engineers server config directory
  file:
    path: "/workspace/spaceengineers/DedicatedServer64"
    state: directory
    mode: '0755'

- name: Render SpaceEngineersDedicated.cfg with vars
  template:
    src: "templates/SpaceEngineersDedicated.cfg.j2"
    dest: "/workspace/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.cfg"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Copy systemd service file for Space Engineers server
  copy:
    src: "files/spaceengineers.service"
    dest: "/etc/systemd/system/spaceengineers.service"
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to recognize the new service
  systemd:
    daemon_reload: yes

- name: Enable and start Space Engineers server service
  systemd:
    name: spaceengineers
    enabled: yes
    state: started

- name: Verify Space Engineers server service is running
  command: systemctl is-active spaceengineers
  register: service_status
  failed_when: service_status.stdout.strip() != "active"

- name: Configure logrotate for Space Engineers logs
  copy:
    content: |
      /workspace/spaceengineers/logs/*.log {
        daily
        missingok
        rotate 14
        compress
        notifempty
        create 0640 ubuntu ubuntu
      }
    dest: /etc/logrotate.d/spaceengineers
    owner: root
    group: root
    mode: '0644'