---
- name: SE server configuration
  become: True
  hosts: se_server
  vars_files:
    # User defined variables
    - vars.yml
    # secrets
    - secrets.yml

  roles:
    - role: se_server_config/0-basic-dependencies
    - role: se_server_config/1-se-server-config
    # - role: se_server_config/2-server-setup
