# wine
wine_branch: 'stable'
wine_version: '9.0.0.0~bookworm-1'
wine_arch: 'win64'
wine_debug: '-all'
wine_prefix: '/root/server'
apt_key_dont_warn_on_dangerous_usage: '1'

# debian
debian_frontend: 'noninteractive'

# instance
instance_name: 'SE_TEST'

# paths
home_dir: '/appdata/space-engineers'
plugin_dir: '{{ home_dir }}/plugins'
instance_dir: '{{ home_dir }}/instances'
instance_home_dir: '{{ instance_dir }}/{{instance_name}}'
game_dir: '{{ home_dir }}/SpaceEngineersDedicated'
steamcmd_dir: '{{ home_dir }}/steamcmd'
config_dir: '{{ instance_home_dir }}/SpaceEngineers-Dedicated.cfg'



# # se_server
# server_name: MyDumpsterFireServer
# server_description: Welcome to the DumpsterFire!
# max_players: 4
# server_port: 27016
# world_name: MyWorld
# world_size: 8
# mod_ids: "484504816"
# game_mode: Survival
# pve: true
