name: se-server-config

on:
  workflow_dispatch:
    inputs:
        ANSIBLE_IMAGE_VERSION:
          description: 'Enter a custom tag'
          required: true
          default: '1.0.0_00-30-14-12-2024'
          type: choice
          options:
            - 1.0.0_00-30-14-12-2024
            - latest

env:
  ANSIBLE_IMAGE_VERSION: ${{ github.event.inputs.ANSIBLE_IMAGE_VERSION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Ansible Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }}

    - name: Setup SSH Key
      run: |
        mkdir -p $GITHUB_WORKSPACE/keys
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/keys/se_server_ec2_key.pem
        chmod 600 $GITHUB_WORKSPACE/keys/se_server_ec2_key.pem

    - name: Run Ansible Playbook
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        ANSIBLE_PRIVATE_KEY: $GITHUB_WORKSPACE/keys/se_server_ec2_key.pem
      run: |
        docker run --rm \
          -e ansible_private_key=$GITHUB_WORKSPACE/keys/se_server_ec2_key.pem \
          -e ec2_public_ip=${{ secrets.EC2_PUBLIC_IP }} \
          -v $GITHUB_WORKSPACE/ansible:/workspace/ansible \
          -v $GITHUB_WORKSPACE/keys:/workspace/keys \
          ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }}
          ansible-playbook -i $GITHUB_WORKSPACE/ansible/inventory.yml $GITHUB_WORKSPACE/ansible/se-server-config.yml --check



    # - name: Test
    #   run: |
    #     cd $GITHUB_WORKSPACE/keys
    #     ls -l
