name: se-server-config

on:
  workflow_dispatch:
    inputs:
      ANSIBLE_IMAGE_VERSION:
        description: 'Enter a custom tag'
        required: true
        default: '1.0.0_00-30-14-12-2024'
        type: choice
        options:
          - 1.0.0_00-30-14-12-2024
          - latest
      DRY_RUN:
        description: 'Enable Ansible dry-run mode'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  ANSIBLE_IMAGE_VERSION: ${{ github.event.inputs.ANSIBLE_IMAGE_VERSION }}
  DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Ansible Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }}

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/ansible/se_server_ec2_key.pem
        chmod 400 $GITHUB_WORKSPACE/ansible/se_server_ec2_key.pem

    - name: Update Inventory File with EC2_PUBLIC_IP
      run: |
        echo "${{ env.EC2_PUBLIC_IP }}" >> $GITHUB_WORKSPACE/ansible/inventory/se_server

    - name: Test SSH Connection
      run: |
        ssh -i $GITHUB_WORKSPACE/ansible/se_server_ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_PUBLIC_IP }} "echo 'SSH Connection Successful'"


    # - name: Run Ansible Playbook
    #   run: |
    #     DRY_RUN_OPTION=""
    #     if [ "${{ env.DRY_RUN }}" = "true" ]; then
    #         DRY_RUN_OPTION="--check"
    #     fi
    #     cd ansible
    #     docker run --rm \
    #     -v $GITHUB_WORKSPACE/ansible:/ansible \
    #     ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }} \
    #     ansible-playbook /ansible/se-server-config.yml -i /ansible/inventory/se_server $DRY_RUN_OPTION

      
          
