name: se-server-config

on:
  workflow_dispatch:
    inputs:
      ANSIBLE_IMAGE_VERSION:
        description: 'Enter a custom tag'
        required: true
        default: '1.0.0_00-30-14-12-2024'
        type: choice
        options:
          - 1.0.0_00-30-14-12-2024
          - latest
      DRY_RUN:
        description: 'Enable Ansible dry-run mode'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  ANSIBLE_IMAGE_VERSION: ${{ github.event.inputs.ANSIBLE_IMAGE_VERSION }}
  DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Ansible Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }}

    - name: Setup SSH Key
      run: |
        mkdir -p $GITHUB_WORKSPACE/ansible
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/ansible/se_server_ec2_key.pem
        chmod 600 $GITHUB_WORKSPACE/ansible/se_server_ec2_key.pem


    - name: Run Ansible Playbook
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE/ansible:/workspace/ansible \
          ${{ secrets.DOCKER_USERNAME }}/ansible-container:${{ env.ANSIBLE_IMAGE_VERSION }} \
          ansible-playbook /workspace/ansible/se-server-config.yml \
          -i /workspace/ansible/inventory.yml \
          -e "ec2_public_ip=${{ env.EC2_PUBLIC_IP }}" \
          $(if [[ "${{ env.DRY_RUN }}" == "true" ]]; then echo "--check"; fi)
